## Trained on 1 RTX A6000 GPU
## Unet++ NIH training based on NIH pretrained weight generated by gen_pretrain.ipynb script
python run.py lr=3e-4 logger=True project="siim-covid-reproduce" fold=0 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/kaggle_model/train_code_study_2class/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
python run.py lr=3e-4 logger=True project="siim-covid-reproduce" fold=1 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/kaggle_model/train_code_study_2class/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
python run.py lr=3e-4 logger=True project="siim-covid-reproduce" fold=2 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/kaggle_model/train_code_study_2class/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
python run.py lr=3e-4 logger=True project="siim-covid-reproduce" fold=3 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/kaggle_model/train_code_study_2class/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
python run.py lr=3e-4 logger=True project="siim-covid-reproduce" fold=4 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/kaggle_model/train_code_study_2class/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
