## Trained on 1 RTX A6000 GPU
## Efficientnetv2 2class finetuning
python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-reproduce" fold=0 unet_smp.backbone_name=tu-tf_efficientnetv2_l img_size=384 gpus=1 epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/efficientnetv2-l-384/tu_tf_efficientnetv2_l-384-aug-epoch08-sgkf0-val_loss0.7614.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-reproduce" fold=1 unet_smp.backbone_name=tu-tf_efficientnetv2_l img_size=384 gpus=1 epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/efficientnetv2-l-384/tu_tf_efficientnetv2_l-384-aug-epoch04-sgkf1-val_loss0.7402.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-reproduce" fold=2 unet_smp.backbone_name=tu-tf_efficientnetv2_l img_size=384 gpus=1 epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/efficientnetv2-l-384/tu_tf_efficientnetv2_l-384-aug-epoch14-sgkf2-val_loss0.7636.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-reproduce" fold=3 unet_smp.backbone_name=tu-tf_efficientnetv2_l img_size=384 gpus=1 epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/efficientnetv2-l-384/tu_tf_efficientnetv2_l-384-aug-epoch09-sgkf3-val_loss0.7793.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-reproduce" fold=4 unet_smp.backbone_name=tu-tf_efficientnetv2_l img_size=384 gpus=1 epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/efficientnetv2-l-384/tu_tf_efficientnetv2_l-384-aug-epoch03-sgkf4-val_loss0.7819.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
## Swin Transformer 2class finetuning
python run.py lr=1e-5 model=timm_2c logger=True project="siim-covid-reproduce" fold=0 img_size=384 gpus=1 epoch=5 model_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=05-sgkf0-val_loss\=0.8677.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-5 model=timm_2c logger=True project="siim-covid-reproduce" fold=1 img_size=384 gpus=1 epoch=5 model_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=06-sgkf1-val_loss\=0.8142.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-5 model=timm_2c logger=True project="siim-covid-reproduce" fold=2 img_size=384 gpus=1 epoch=5 model_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=04-sgkf2-val_loss\=0.8851.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-5 model=timm_2c logger=True project="siim-covid-reproduce" fold=3 img_size=384 gpus=1 epoch=5 model_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=07-sgkf3-val_loss\=0.8961.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-5 model=timm_2c logger=True project="siim-covid-reproduce" fold=4 img_size=384 gpus=1 epoch=5 model_path="/home/lorenzo/kaggle_model/train_code_study_2class/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=04-sgkf4-val_loss\=0.8842.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
